[package]
name = "mojankinator"
version = "0.1.0"
edition = "2021"
license = "AGPL-3"

[dependencies]
indicatif = "0.17.8"
git2 = "0.20.0"
walkdir = "2.5.0"
linked-hash-map = "0.5.6"
toml = "0.8.19"
error-stack = "0.5.0"
thiserror = "2.0.9"
tempfile = "3.15.0"
zip = "2.2.2"

[dependencies.chrono]
version = "0.4.38"
features = ["serde"]

[dependencies.ureq]
version = "2.10.1"
features = ["json"]

[dependencies.serde]
version = "1.0.214"
features = ["derive"]

[dependencies.owo-colors]
version = "4.1.0"
features = ["supports-colors"]
