[package]
name = "mojankinator"
version = "0.1.0"
edition = "2021"
license = "AGPL-3"

[dependencies]
indicatif = "0.17.11"
git2 = "0.20.1"
walkdir = "2.5.0"
linked-hash-map = "0.5.6"
toml = "0.8.20"
error-stack = "0.5.0"
thiserror = "2.0.12"
tempfile = "3.19.1"
zip = "2.5.0"

[dependencies.chrono]
version = "0.4.40"
features = ["serde"]

[dependencies.ureq]
version = "3.0.10"
features = ["json"]

[dependencies.serde]
version = "1.0.219"
features = ["derive"]

[dependencies.owo-colors]
version = "4.2.0"
features = ["supports-colors"]
